version: '{build}'
os: Visual Studio 2017
shallow_clone: true
init:
  - set PATH=C:\Ruby25\bin;%PATH%
  - git config --global core.autocrlf input
  - git config --global core.longpaths true
install:
  - gem install sass
build_script:
  build.cmd package
test: off
artifacts:
- path: artifacts\*.nupkg
  name: NuGetPackages
deploy: off
